steps:
  - name: ":rubocop:"
    command: bin/rubocop
    timeout_in_minutes: 30
    agents:
      queue: shared

  - name: ":rspec:"
    command: bin/test
    timeout_in_minutes: 30
    agents:
      queue: shared
